CXX = g++
CXXFLAGS = -std=c++20 -I../algo1_lib
LDFLAGS = -rdynamic -ldl

SRCS = main.cpp AlgorithmRegistrar.cpp
OBJS = $(SRCS:.cpp=.o)

all: simulator

simulator: $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $^ -lAlgo_209228600_A

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) simulator