CXX = g++
CXXFLAGS = -std=c++20 -fPIC -shared -fvisibility=hidden -fvisibility-inlines-hidden -Iinclude

SRCS = Algo_209228600_A.cpp
OBJS = $(SRCS:.cpp=.o)

all: libAlgo_209228600_A.so

libAlgo_209228600_A.so: $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) libAlgo_209228600_A.so